stages:                 # Les étapes associées au projet.
  - lint                # Pour la vérification statique du code 
  - deploy              # Deploiement


lint-js:                # Vérification de la qualité du code javascript
  stage: lint           # Dans l'étape lint (s'exécutera en parallèle de lint-html-css)
  tags:
    - docker
  image: node
  script:
    - npm install eslint
    - npx eslint *.js


pages:                  # Job associé à la publication du site
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public/
